// Edge-cache helper for read-only GET endpoints.
//
// Cloudflare does NOT automatically cache responses generated by Pages
// Functions just because they carry a Cache-Control header — that header only
// controls the *browser* cache. To share one response across many users we
// have to store it in the Cloudflare Cache API explicitly. The cache is
// per-location: the first visitor to reach a given data center warms it, and
// everyone after that gets a hit with no D1 round trip until the TTL expires.
// That is what makes load times consistent worldwide instead of every request
// reaching across the planet to the single D1 region.
//
// Usage:
//   return withEdgeCache(context, { maxAge: 60 }, async () => {
//     ...build and return a Response...
//   });
//
// Only successful (200) GET responses are cached, so a transient error is
// never stored. Pass `key` to override the cache key (defaults to the full
// request URL, so query-string variants cache separately).

export async function withEdgeCache(context, { maxAge, key } = {}, compute) {
  const { request, waitUntil } = context;

  // Only idempotent GETs are safe to serve from a shared cache.
  if (request.method !== 'GET') return compute();

  const cache = caches.default;
  const cacheUrl = key ? new URL(key, request.url).toString() : request.url;
  const cacheKey = new Request(cacheUrl, { method: 'GET' });

  const hit = await cache.match(cacheKey);
  if (hit) return hit;

  const response = await compute();

  if (response.status === 200) {
    // This header drives both the browser cache and the Cache API TTL.
    response.headers.set('Cache-Control', `public, max-age=${maxAge}`);
    // Store a clone and stream the original back; waitUntil keeps the write
    // alive after the response has been returned to the caller.
    waitUntil(cache.put(cacheKey, response.clone()));
  }

  return response;
}
